### ISSUE TITLE
[Bug] An unhandled error occurred: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by draylegend** [zenstackhq/zenstack#1154]
### Error

```js
$ node index.js 
Example app listening on port 3000
/home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:773
        for (const model of Object.keys(modelMeta.fields)) {
                                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at RequestHandler.buildSerializers (/home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:773:36)
    at RequestHandler.<anonymous> (/home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:172:22)
    at Generator.next (<anonymous>)
    at /home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:4:12)
    at RequestHandler.handleRequest (/home/dl/express-zenstack/node_modules/@zenstackhq/server/api/rest/index.js:166:16)
    at Object.<anonymous> (/home/dl/express-zenstack/index.js:17:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

### Description

In [L959](https://github.com/zenstackhq/zenstack/blob/main/packages/server/src/api/rest/index.ts#L959) & [L1016](https://github.com/zenstackhq/zenstack/blob/main/packages/server/src/api/rest/index.ts#L1016) `Object.keys` gets undefined property `modelMeta.fields`. For some reason the `modelMeta.fields` property doesn't exists in

```js
// node_modules/.zenstack/model-meta.js

const metadata = {
  models: {
    user: {
      name: 'User',
      fields: [Object],
      uniqueConstraints: [Object],
      attributes: [Array]
    },
    post: {
      name: 'Post',
      fields: [Object],
      uniqueConstraints: [Object],
      attributes: [Array]
    }
  },
  deleteCascade: {},
  authModel: 'User'
};
```

### Usage

```ts
// main.ts

import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { PrismaService } from '@virtum.club/shared-api';
import { enhance } from '@zenstackhq/runtime';
import handler from '@zenstackhq/server/api/rest';
import { ZenStackMiddleware } from '@zenstackhq/server/express';

import { AppModule } from './app/app.module';

(async () => {
  const app = await NestFactory.create(AppModule, {
    cors: { origin: 'localhost:4200/*' },
  });
  const port = process.env.PORT || 3000;

  app.use(
    ZenStackMiddleware({
      getPrisma: () =>
        enhance(app.get(PrismaService), {
          user: { id: 'clto63ntl0001r4typdtwbwfx' },
        }),
      handler: handler({
        endpoint: `http://localhost:${port}`,
      }),
    }),
  );
  await app.listen(port);

  Logger.log(`🚀 http://localhost:${port}`);
})();
```

### Environment

-   ZenStack version: 2.0.0-beta.1
-   Prisma version: 5.11.0
-   Database type: sqlite

**Comment by ymc9** [comment]
Hi @draylegend , could you check if you're using v1 of `@zenstackhq/server` package with v2 CLI/runtime?

**Comment by draylegend** [comment]
@ymc9 thanks for swift answer! For some reason I had the server v1. Updating all `❤️ zenstack ❤️` packages to the next version solves the issue.
Closing
