### ISSUE TITLE
Linker exception for multiple file with abstact models for V2

### ISSUE THREAD

**Issue by jiashengguo** [zenstackhq/zenstack#1210]
[zens.zip](https://github.com/zenstackhq/zenstack/files/14834639/zens.zip)

Running `zenstack generate` for the above schema will show the error:
```bash
An unexpected error occurred:
 TypeError: Cannot read properties of undefined (reading 'type')
    at ZModelLinker.resolveToDeclaredType (/app/node_modules/zenstack/language-server/zmodel-linker.js:414:18)
    at ZModelLinker.resolveReference (/app/node_modules/zenstack/language-server/zmodel-linker.js:170:22)
    at ZModelLinker.resolve (/app/node_modules/zenstack/language-server/zmodel-linker.js:81:22)
    at ZModelLinker.resolveBinary (/app/node_modules/zenstack/language-server/zmodel-linker.js:136:22)
    at ZModelLinker.resolve (/app/node_modules/zenstack/language-server/zmodel-linker.js:90:22)
    at ZModelLinker.resolveAttributeArg (/app/node_modules/zenstack/language-server/zmodel-linker.js:328:18)
    at ZModelLinker.resolve (/app/node_modules/zenstack/language-server/zmodel-linker.js:102:22)
    at ZModelLinker.resolveDefault (/app/node_modules/zenstack/language-server/zmodel-linker.js:399:18)
    at ZModelLinker.resolve (/app/node_modules/zenstack/language-server/zmodel-linker.js:111:22)
    at ZModelLinker.resolveDefault (/app/node_modules/zenstack/language-server/zmodel-linker.js:399:18)
```

It happens for 2.0.0-beta.5, but works in V1.

**Comment by ymc9** [comment]
Fixed in 2.0.0-beta.8
