### ISSUE TITLE
[BUG?] Model inheritance seeding fails due to incorrect arguments in prisma call

### ISSUE THREAD

**Issue by kennyboy55** [zenstackhq/zenstack#1392]
**Description and expected behavior**
I have a model using the new table inheritance feature. When trying to seed this database, the enhanced call is adding a argument to the prisma call that is not recognized.

Model:
```typescript
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum DrinkType {
  Drink
  Beer
  Wine
  Soda
}

enum ContainerType {
  BeerBottle
  WineBottle
  PlasticBottle
  Can
  Carton
}

model Drink {
  id                Int   @id @default(autoincrement())
  slug              String @unique

  manufacturer_id   Int
  manufacturer      Manufacturer @relation(fields: [manufacturer_id], references: [id])

  type              DrinkType

  name              String @unique
  description       String
  abv               Float
  image             String?

  containers        Container[]

  @@delegate(type)

  @@allow('all', true)
}

model Beer extends Drink {
  style_id         Int
  style            BeerStyle @relation(fields: [style_id], references: [id])

  ibu              Float?

  @@allow('all', true)
}

model BeerStyle {
  id               Int @id @default(autoincrement())

  name             String @unique

  beers            Beer[]

  @@allow('all', true)
}

model Wine extends Drink {
  style_id         Int
  style            WineStyle @relation(fields: [style_id], references: [id])

  heavy_score      Int?
  tannine_score    Int?
  dry_score        Int?
  fresh_score      Int?
  notes            String?

  @@allow('all', true)
}

model WineStyle {
  id               Int @id @default(autoincrement())

  name             String @unique

  wines            Wine[]

  @@allow('all', true)
}

model Soda extends Drink {
  carbonated       Boolean

  @@allow('all', true)
}

model Container {
  barcode          String @id
  
  drink_id         Int
  drink            Drink @relation(fields: [drink_id], references: [id])

  type             ContainerType
  volume           Int
  portions         Int?

  inventory        Int @default(0)

  @@allow('all', true)
}

model Manufacturer {
  id               Int   @id @default(autoincrement())

  country_id       String
  country          Country @relation(fields: [country_id], references: [code])

  name             String @unique
  image            String?

  drinks            Drink[]

  @@allow('all', true)
}

model Country {
  code             String @id
  name             String

  manufacturers    Manufacturer[]

  @@allow('all', true)
}
``` 
Seed:
```typescript
import { ContainerType, DrinkType, PrismaClient } from "@prisma/client";
import { enhance } from "@zenstackhq/runtime";
const pr = new PrismaClient();
const db = enhance(pr);

async function seed() {

  await db.container.deleteMany({});
  await db.beer.deleteMany({});
  await db.beerStyle.deleteMany({});
  await db.manufacturer.deleteMany({});
  await db.country.deleteMany({});

  await Promise.all(
    getCountries().map((country) => {
      return db.country.create({ data: country });
    })
  );

  await Promise.all(
    getManufacturers().map((man) => {
      return db.manufacturer.create({ data: man });
    })
  );

  await Promise.all(
    getBeerStyles().map((style) => {
      return db.beerStyle.create({ data: style });
    })
  );

  await Promise.all(
    getBeers().map((beer) => {
      return db.beer.create({ data: beer });
    })
  );

  await Promise.all(
    getContainers().map((container) => {
      return db.container.create({ data: container });
    })
  );
}

seed();

function getCountries(){
  return [
    {
      code: "nl",
      name: "Netherlands"
    },
    {
      code: "de",
      name: "Germany"
    },
    {
      code: "be",
      name: "Belgium"
    }
  ];
}

function getManufacturers(){
  return [
    {
      id: 1,
      country_id: "nl",
      name: "Hertog Jan"
    },
    {
      id: 2,
      country_id: "nl",
      name: "Heineken"
    },
    {
      id: 3,
      country_id: "nl",
      name: "Jupiler"
    },
    {
      id: 4,
      country_id: "nl",
      name: "Brouwerij Het IJ"
    }
  ];
}

function getBeerStyles(){
  return [
    {
      id: 1,
      name: "Pilsener",
    },
    {
      id: 2,
      name: "Dubbel"
    },
    {
      id: 3,
      name: "Tripel"
    }
  ];
}

function getBeers() {
  return [
    {
      id: 1,
      slug: "ginger_paradise",
      name: "Ginger Paradise",
      abv: 6.2,
      ibu: 5,

      manufacturer_id: 4,
      style_id: 3,

      description: "Some desciption on why this beer is so great and it has this and that flavour",
    }
  ];
}

function getContainers() {
  return [
    {
      barcode: "temporary1",
      drink_id: 1,
      type: ContainerType.BeerBottle,
      volume: 330,
      portions: 1
    }
  ];
}
``` 
Error:
```shell
npx prisma db seed
Environment variables loaded from .env
Running seed command `tsx prisma/seed.ts` ...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error calling enhanced Prisma method `beer.create`: 
Invalid `prisma.beer.create()` invocation:

{
  data: {
    id: 1,
    ibu: 5,
    style_id: 3,
    delegate_aux_drink: {
    ~~~~~~~~~~~~~~~~~~
      create: {
        type: "Beer",
        slug: "ginger_paradise",
        name: "Ginger Paradise",
        abv: 6.2,
        manufacturer_id: 4,
        description: "Some desciption on why this beer is so great and it has this and that flavour"
      }
    }
  },
  select: {
    id: true
  }
}

Unknown argument `delegate_aux_drink`. Available options are marked with ?.
    at <anonymous> (/home/keewijk/projects/beer-inventory/prisma/seed.ts:34:22),
    at Array.map (<anonymous>),
    at seed (/home/keewijk/projects/beer-inventory/prisma/seed.ts:33:16) {
  name: 'PrismaClientValidationError',
  clientVersion: '5.13.0',
  internalStack: 'Error calling enhanced Prisma method `beer.create`: \n' +
    'Invalid `prisma.beer.create()` invocation:\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    '    id: 1,\n' +
    '    ibu: 5,\n' +
    '    style_id: 3,\n' +
    '    delegate_aux_drink: {\n' +
    '    ~~~~~~~~~~~~~~~~~~\n' +
    '      create: {\n' +
    '        type: "Beer",\n' +
    '        slug: "ginger_paradise",\n' +
    '        name: "Ginger Paradise",\n' +
    '        abv: 6.2,\n' +
    '        manufacturer_id: 4,\n' +
    '        description: "Some desciption on why this beer is so great and it has this and that flavour"\n' +
    '      }\n' +
    '    }\n' +
    '  },\n' +
    '  select: {\n' +
    '    id: true\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Unknown argument `delegate_aux_drink`. Available options are marked with ?.\n' +
    '    at PolicyProxyHandler.<anonymous> (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/policy/handler.ts:203:57),\n' +
    '    at Generator.next (<anonymous>),\n' +
    '    at <anonymous> (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/policy/handler.ts:1:56),\n' +
    '    at new Promise (<anonymous>),\n' +
    '    at __awaiter (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/policy/handler.ts:1:56),\n' +
    '    at <anonymous> (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/policy/handler.ts:185:99),\n' +
    '    at fullDb.$transaction.maxWait (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/query-utils.ts:45:28),\n' +
    '    at <anonymous> (/home/keewijk/projects/beer-inventory/node_modules/@zenstackhq/src/enhancements/proxy.ts:223:36),\n' +
    '    at Proxy._transactionWithCallback (/home/keewijk/projects/beer-inventory/node_modules/@prisma/client/runtime/library.js:127:9540)'
}

Node.js v22.0.0

An error occurred while running the seed command:
Error: Command failed with exit code 1: tsx prisma/seed.ts
``` 

**Environment (please complete the following information):**

-   ZenStack version: 2.0.1
-   Prisma version: 5.13.0
-   Database type: Postgresql

**Comment by ymc9** [comment]
Hi @kennyboy55 , thanks for reporting this! It looks like a bug to me. I'll look into it and share my findings soon.

**Comment by kennyboy55** [comment]
I fixed it by changing my seed script to use `connect: { id: ?}}` instead of raw ids.

```typescript
function getBeers() {
  return [
    {
      slug: "ginger_paradise",
      name: "Ginger Paradise",
      abv: 6.2,
      ibu: 5,

      manufacturer: {connect: { id: 4}},
      style: {connect: { id: 3}},

      description: "Some desciption on why this beer is so great and it has this and that flavour",
    }
  ];
}
```
