### ISSUE TITLE
CompileError: WebAssembly.Module()

### ISSUE THREAD

**Issue by JosephSaleon** [zenstackhq/zenstack#1616]
npx zenstack@latest init won't work for me. This is the error I received:

AppData\Local\npm-cache\_npx\aded272cd7beac82\node_modules\@prisma\prisma-schema-wasm\src\prisma_schema_build.js:513
const wasmModule = new WebAssembly.Module(bytes);
                   ^

CompileError: WebAssembly.Module(): section (code 10, "Code") extends past end of the module (length 1817800, remaining bytes 1161996) @+6682
    at Object.<anonymous> (C:\Users\josep\AppData\Local\npm-cache\_npx\aded272cd7beac82\node_modules\@prisma\prisma-schema-wasm\src\prisma_schema_build.js:513:20)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (C:\Users\josep\AppData\Local\npm-cache\_npx\aded272cd7beac82\node_modules\@prisma\internals\dist\chunk-W65Z4BE5.js:39:41)

Node.js v22.5.1

I tried to clean the npm cache.
I tried to reinstall Node.
I tried to update Prisma.
I tried different versions of Node: 22.5.1, 20.16.0, 18.0.0.
I tried with a fresh T3 project.
Nothing worked, always the same error.

So, I installed it manually, and it finally worked.

T3Stack 
Node: 22.5.1, 20.16.0, 18.0.0

**Comment by ymc9** [comment]
@jiashengguo , could you try T3 on windows with latest version when you have time?
