### ISSUE TITLE
RESTful API RESULT_NOT_READABLE status

### ISSUE THREAD

**Issue by Tsimopak** [zenstackhq/zenstack#1649]
**Description and expected behavior**
I made a clone of the following : git clone --branch part3 https://github.com/zenstackhq/the-complete-guide-sample.git my-todo-app

i installed everything and then i started the server, and when i tried to use the following http reqeust (i use REST Client vscode extension):

```
POST http://localhost:3000/api/rest/user HTTP/1.1
content-type: application/json

{
  "data": {
    "type": "user",
    "attributes": {
      "email": "test10@gmail.com"
    }
  }
}
```

I got an error:
```
HTTP/1.1 403 Forbidden
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 110
ETag: W/"6e-tfEela+mUZUzPGGhw413HgfJj1k"
Date: Wed, 21 Aug 2024 08:11:47 GMT
Connection: close

{
  "errors": [
    {
      "status": 403,
      "code": "forbidden",
      "title": "Operation is forbidden",
      "reason": "RESULT_NOT_READABLE"
    }
  ]
}
```
But it does push it to database, why is that?

NOTE: when I try to use instead of application/json the following attribute: application/vnd.api+json, i get the following error:
```
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 1323
ETag: W/"52b-LifTBE1RJMGUHhKlNZ7cViRERSI"
Date: Wed, 21 Aug 2024 08:12:37 GMT
Connection: close

{
  "errors": [
    {
      "status": 400,
      "code": "unknown-error",
      "title": "Unknown error",
      "detail": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"data\"\n    ],\n    \"message\": \"Required\"\n  }\n]\nZodError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"data\"\n    ],\n    \"message\": \"Required\"\n  }\n]\n    at get error [as error] (/Users/project/tests/my-todo-app/node_modules/zod/lib/types.js:55:31)\n    at ZodObject.parse (/Users/project/tests/my-todo-app/node_modules/zod/lib/types.js:160:22)\n    at RequestHandler.processRequestBody (/Users/project/tests/my-todo-app/node_modules/@zenstackhq/src/api/rest/index.ts:692:55)\n    at RequestHandler.processCreate (/Users/project/tests/my-todo-app/node_modules/@zenstackhq/src/api/rest/index.ts:730:59)\n    at RequestHandler.handleRequest (/Users/project/tests/my-todo-app/node_modules/@zenstackhq/src/api/rest/index.ts:293:43)\n    at <anonymous> (/Users/project/tests/my-todo-app/node_modules/@zenstackhq/src/express/middleware.ts:57:29)\n    at <anonymous> (/Users/project/tests/my-todo-app/main.ts:41:5)"
    }
  ]
}
```

**Environment (please complete the following information):**
npm list             
script@ /Users/project/tests/my-todo-app
├── @prisma/client@5.18.0
├── @types/express@4.17.21
├── @types/node@20.10.1
├── @types/swagger-ui-express@4.1.6
├── @zenstackhq/openapi@2.4.1
├── @zenstackhq/runtime@2.4.1
├── @zenstackhq/server@2.4.1
├── express@4.19.2
├── prisma@5.18.0
├── swagger-ui-express@5.0.1
├── ts-node@10.9.1
├── tsx@4.17.0
├── typescript@5.3.2
└── zenstack@2.4.1
-   Database type: sqlite

**Comment by Tsimopak** [comment]
Okay it happened because my `@allow` policy wasn't explict included read true or all true, after doing so it worked.
