### ISSUE TITLE
npx zenstack generate doesn't work, maximum call stack errors. 

### ISSUE THREAD

**Issue by daveycodez** [zenstackhq/zenstack#1917]
I tried to add ZenStack to my existing NextJS project. It's brand new with create-next-app@latest.

All I do is run these 2 commands and it fails.

```shell
npx zenstack@latest init
Installing package "zenstack@2.10.1" with npm

added 121 packages, and audited 856 packages in 5s

200 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing package "@zenstackhq/runtime@2.10.1" with npm

up to date, audited 856 packages in 1s

200 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Sample model generated at: schema.zmodel

Please check the following guide on how to model your app:
    https://zenstack.dev/#/modeling-your-app.

Project initialized successfully!
```

```shell
npx zenstack generate

An unexpected error occurred:
 RangeError: Maximum call stack size exceeded
    at Rule.get (/Users/david/Developer/new-tech/node_modules/langium/node_modules/@chevrotain/gast/lib/src/model.js:46:23)
    at NonTerminal.get (/Users/david/Developer/new-tech/node_modules/langium/node_modules/@chevrotain/gast/lib/src/model.js:75:44)
    at block (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:68)
    at atom (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:130:16)
    at /Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:87
    at arrayMap (/Users/david/Developer/new-tech/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/david/Developer/new-tech/node_modules/lodash/map.js:50:10)
    at block (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:61)
    at atom (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:130:16)
    at /Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:87

An unexpected error occurred:
 RangeError: Maximum call stack size exceeded
    at Rule.get (/Users/david/Developer/new-tech/node_modules/langium/node_modules/@chevrotain/gast/lib/src/model.js:46:23)
    at NonTerminal.get (/Users/david/Developer/new-tech/node_modules/langium/node_modules/@chevrotain/gast/lib/src/model.js:75:44)
    at block (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:68)
    at atom (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:130:16)
    at /Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:87
    at arrayMap (/Users/david/Developer/new-tech/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/david/Developer/new-tech/node_modules/lodash/map.js:50:10)
    at block (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:61)
    at atom (/Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:130:16)
    at /Users/david/Developer/new-tech/node_modules/chevrotain-allstar/lib/atn.js:185:87
```

I'm on macOS if that matters.

**Comment by daveycodez** [comment]
I did some research and it might be a specific issue with ARM based Macs.

https://github.com/lovell/sharp/issues/3944

Someone had this error only on an arm Mac with Sharp

**Comment by ymc9** [comment]
HI @daveycodez , could you help check the versions of "langium" and "chevrotain*" in your project? I suspect it's due to a version mismatch.

```bash
npm ls langium
npm ls -a | grep chevrotain
```

**Comment by daveycodez** [comment]
```shell
npm ls langium
npm ls -a | grep chevrotain
new-tech@0.1.0 /Users/david/Developer/new-tech
└─┬ zenstack@2.10.2
  ├─┬ @zenstackhq/language@2.10.2
  │ └── langium@1.3.1 deduped
  ├─┬ @zenstackhq/sdk@2.10.2
  │ └── langium@1.3.1 deduped
  └── langium@1.3.1

│ │ ├─┬ chevrotain@10.5.0
│ │ │ ├─┬ @chevrotain/cst-dts-gen@10.5.0
│ │ │ │ ├── @chevrotain/gast@10.5.0 deduped
│ │ │ │ ├── @chevrotain/types@10.5.0 deduped
│ │ │ ├─┬ @chevrotain/gast@10.5.0
│ │ │ │ ├── @chevrotain/types@10.5.0 deduped
│ │ │ ├── @chevrotain/types@10.5.0
│ │ │ ├── @chevrotain/utils@10.5.0
│ │ ├─┬ chevrotain-allstar@0.1.7
│ │ │ ├── chevrotain@10.5.0 deduped invalid: "~10.4.1" from node_modules/chevrotain-allstar
│ │ ├─┬ chevrotain@10.4.2
│ │ │ ├─┬ @chevrotain/cst-dts-gen@10.4.2
│ │ │ │ ├── @chevrotain/gast@10.4.2 deduped
│ │ │ │ ├── @chevrotain/types@10.4.2 deduped
│ │ │ ├─┬ @chevrotain/gast@10.4.2
│ │ │ │ ├── @chevrotain/types@10.4.2 deduped
│ │ │ ├── @chevrotain/types@10.4.2
│ │ │ ├── @chevrotain/utils@10.4.2
npm error code ELSPROBLEMS
npm error extraneous: @emnapi/core@0.45.0 /Users/david/Developer/new-tech/node_modules/@emnapi/core
npm error extraneous: @emnapi/runtime@0.45.0 /Users/david/Developer/new-tech/node_modules/@emnapi/runtime
npm error extraneous: @tybys/wasm-util@0.8.3 /Users/david/Developer/new-tech/node_modules/@tybys/wasm-util
npm error extraneous: fs-monkey@1.0.6 /Users/david/Developer/new-tech/node_modules/fs-monkey
npm error extraneous: memfs-browser@3.5.10302 /Users/david/Developer/new-tech/node_modules/memfs-browser
npm error extraneous: memfs@3.5.3 /Users/david/Developer/new-tech/node_modules/memfs
npm error invalid: @types/react@19.0.2 /Users/david/Developer/new-tech/node_modules/@types/react
npm error invalid: chevrotain@10.5.0 /Users/david/Developer/new-tech/node_modules/chevrotain
npm error A complete log of this run can be found in: /Users/david/.npm/_logs/2024-12-20T01_53_11_261Z-debug-0.log
```

**Comment by ymc9** [comment]
Thanks for sharing this. It seems there're two versions of chevrotain installed, but I couldn't reproduce the issue locally after installing both. Do you have a sharable repro project?

**Comment by draylegend** [comment]
### error

```js
 RangeError: Maximum call stack size exceeded
    at Object.get [as Terminal] (/home/dl/my-project/node_modules/chevrotain-allstar/node_modules/chevrotain/lib/src/api.js:51:78)      
    at atom (/home/dl/my-project/node_modules/chevrotain-allstar/lib/atn.js:105:44)
    at /home/dl/my-project/node_modules/chevrotain-allstar/lib/atn.js:185:87
    at arrayMap (/home/dl/my-project/node_modules/lodash/_arrayMap.js:16:21)
    at map (/home/dl/my-project/node_modules/lodash/map.js:50:10)
    at block (/home/dl/my-project/node_modules/chevrotain-allstar/lib/atn.js:185:61)
    at atom (/home/dl/my-project/node_modules/chevrotain-allstar/lib/atn.js:130:16)
    at /home/dl/my-project/node_modules/chevrotain-allstar/lib/atn.js:185:87
    at arrayMap (/home/dl/my-project/node_modules/lodash/_arrayMap.js:16:21)
    at map (/home/dl/my-project/node_modules/lodash/map.js:50:10)
```

### bun.lock

Irrelevant packages ommited

```json
{
  "lockfileVersion": 1,
  "packages": {
    "@chevrotain/cst-dts-gen": ["@chevrotain/cst-dts-gen@10.5.0", "", { "dependencies": { "@chevrotain/gast": "10.5.0", "@chevrotain/types": "10.5.0", "lodash": "4.17.21" } }, "sha512-lhmC/FyqQ2o7pGK4Om+hzuDrm9rhFYIJ/AXoQBeongmn870Xeb0L6oGEiuR8nohFNL5sMaQEJWCxr1oIVIVXrw=="],

    "@chevrotain/gast": ["@chevrotain/gast@10.5.0", "", { "dependencies": { "@chevrotain/types": "10.5.0", "lodash": "4.17.21" } }, "sha512-pXdMJ9XeDAbgOWKuD1Fldz4ieCs6+nLNmyVhe2gZVqoO7v8HXuHYs5OV2EzUtbuai37TlOAQHrTDvxMnvMJz3A=="],

    "@chevrotain/types": ["@chevrotain/types@10.5.0", "", {}, "sha512-f1MAia0x/pAVPWH/T73BJVyO2XU5tI4/iE7cnxb7tqdNTNhQI3Uq3XkqcoteTmD4t1aM0LbHCJOhgIDn07kl2A=="],

    "@chevrotain/utils": ["@chevrotain/utils@10.5.0", "", {}, "sha512-hBzuU5+JjB2cqNZyszkDHZgOSrUUT8V3dhgRl8Q9Gp6dAj/H5+KILGjbhDpc3Iy9qmqlm/akuOI2ut9VUtzJxQ=="],

    "@mrleebo/prisma-ast": ["@mrleebo/prisma-ast@0.12.1", "", { "dependencies": { "chevrotain": "^10.5.0", "lilconfig": "^2.1.0" } }, "sha512-JwqeCQ1U3fvccttHZq7Tk0m/TMC6WcFAQZdukypW3AzlJYKYTGNVd1ANU2GuhKnv4UQuOFj3oAl0LLG/gxFN1w=="],

    "chevrotain": ["chevrotain@10.5.0", "", { "dependencies": { "@chevrotain/cst-dts-gen": "10.5.0", "@chevrotain/gast": "10.5.0", "@chevrotain/types": "10.5.0", "@chevrotain/utils": "10.5.0", "lodash": "4.17.21", "regexp-to-ast": "0.5.0" } }, "sha512-Pkv5rBY3+CsHOYfV5g/Vs5JY9WTHHDEKOlohI2XeygaZhUeqhAlldZ8Hz9cRmxu709bvS08YzxHdTPHhffc13A=="],

    "chevrotain-allstar": ["chevrotain-allstar@0.1.7", "", { "dependencies": { "lodash": "^4.17.21" }, "peerDependencies": { "chevrotain": "~10.4.1" } }, "sha512-oMSHkXVCDQxnj3tDCqcEoMnNIEiYlAYT0FVja1PaLrT3njXGvg5JXTXs/tk2NI42SR3LMJyqTNgjR4VyDIf19w=="],

    "langium": ["langium@1.3.1", "", { "dependencies": { "chevrotain": "~10.4.2", "chevrotain-allstar": "~0.1.4", "vscode-languageserver": "~8.0.2", "vscode-languageserver-textdocument": "~1.0.8", "vscode-uri": "~3.0.7" } }, "sha512-xC+DnAunl6cZIgYjRpgm3s1kYAB5/Wycsj24iYaXG9uai7SgvMaFZSrRvdA5rUK/lSta/CRvgF+ZFoEKEOFJ5w=="],

    "chevrotain-allstar/chevrotain": ["chevrotain@10.4.2", "", { "dependencies": { "@chevrotain/cst-dts-gen": "10.4.2", "@chevrotain/gast": "10.4.2", "@chevrotain/types": "10.4.2", "@chevrotain/utils": "10.4.2", "lodash": "4.17.21", "regexp-to-ast": "0.5.0" } }, "sha512-gzF5GxE0Ckti5kZVuKEZycLntB5X2aj9RVY0r4/220GwQjdnljU+/t3kP74/FMWC7IzCDDEjQ9wsFUf0WCdSHg=="],

    "langium/chevrotain": ["chevrotain@10.4.2", "", { "dependencies": { "@chevrotain/cst-dts-gen": "10.4.2", "@chevrotain/gast": "10.4.2", "@chevrotain/types": "10.4.2", "@chevrotain/utils": "10.4.2", "lodash": "4.17.21", "regexp-to-ast": "0.5.0" } }, "sha512-gzF5GxE0Ckti5kZVuKEZycLntB5X2aj9RVY0r4/220GwQjdnljU+/t3kP74/FMWC7IzCDDEjQ9wsFUf0WCdSHg=="],

    "chevrotain-allstar/chevrotain/@chevrotain/cst-dts-gen": ["@chevrotain/cst-dts-gen@10.4.2", "", { "dependencies": { "@chevrotain/gast": "10.4.2", "@chevrotain/types": "10.4.2", "lodash": "4.17.21" } }, "sha512-0+4bNjlndNWMoVLH/+y4uHnf6GrTipsC+YTppJxelVJo+xeRVQ0s2PpkdDCVTsu7efyj+8r1gFiwVXsp6JZ0iQ=="],

    "chevrotain-allstar/chevrotain/@chevrotain/gast": ["@chevrotain/gast@10.4.2", "", { "dependencies": { "@chevrotain/types": "10.4.2", "lodash": "4.17.21" } }, "sha512-4ZAn8/mjkmYonilSJ60gGj1tAF0cVWYUMlIGA0e4ATAc3a648aCnvpBw7zlPHDQjFp50XC13iyWEgWAKiRKTOA=="],

    "chevrotain-allstar/chevrotain/@chevrotain/types": ["@chevrotain/types@10.4.2", "", {}, "sha512-QzSCjg6G4MvIoLeIgOiMR0IgzkGEQqrNJJIr3T5ETRa7l4Av4AMIiEctV99mvDr57iXwwk0/kr3RJxiU36Nevw=="],

    "chevrotain-allstar/chevrotain/@chevrotain/utils": ["@chevrotain/utils@10.4.2", "", {}, "sha512-V34dacxWLwKcvcy32dx96ADJVdB7kOJLm7LyBkBQw5u5HC9WdEFw2G17zml+U3ivavGTrGPJHl8o9/UJm0PlUw=="],

    "langium/chevrotain/@chevrotain/cst-dts-gen": ["@chevrotain/cst-dts-gen@10.4.2", "", { "dependencies": { "@chevrotain/gast": "10.4.2", "@chevrotain/types": "10.4.2", "lodash": "4.17.21" } }, "sha512-0+4bNjlndNWMoVLH/+y4uHnf6GrTipsC+YTppJxelVJo+xeRVQ0s2PpkdDCVTsu7efyj+8r1gFiwVXsp6JZ0iQ=="],

    "langium/chevrotain/@chevrotain/gast": ["@chevrotain/gast@10.4.2", "", { "dependencies": { "@chevrotain/types": "10.4.2", "lodash": "4.17.21" } }, "sha512-4ZAn8/mjkmYonilSJ60gGj1tAF0cVWYUMlIGA0e4ATAc3a648aCnvpBw7zlPHDQjFp50XC13iyWEgWAKiRKTOA=="],

    "langium/chevrotain/@chevrotain/types": ["@chevrotain/types@10.4.2", "", {}, "sha512-QzSCjg6G4MvIoLeIgOiMR0IgzkGEQqrNJJIr3T5ETRa7l4Av4AMIiEctV99mvDr57iXwwk0/kr3RJxiU36Nevw=="],

    "langium/chevrotain/@chevrotain/utils": ["@chevrotain/utils@10.4.2", "", {}, "sha512-V34dacxWLwKcvcy32dx96ADJVdB7kOJLm7LyBkBQw5u5HC9WdEFw2G17zml+U3ivavGTrGPJHl8o9/UJm0PlUw=="],
  }
}
```

Looks like `langium/chevrotain` is on `10.4.2` and not on `10.5.0`. Could it be the issue?

**Comment by draylegend** [comment]
looks like this issue is appearing only if I install @better-auth/cli. Not sure which lib is outdated or stuff

**Comment by daveycodez** [comment]
Whoaaaa I also had better Auth maybe that’s what’s causing a compatibility issue

**Comment by daveycodez** [comment]
@bekacru might be worth looking into

**Comment by draylegend** [comment]
maybe sometime we'll get a standalone better auth cli for local usage

**Comment by ymc9** [comment]
I tried messing around with my chevrotain versions but still couldn't reproduce the issue. Does anyone have a sharable repro?

**Comment by draylegend** [comment]
> I tried messing around with my chevrotain versions but still couldn't reproduce the issue. Does anyone have a sharable repro?

@ymc9 Did you try to install @better-auth/cli in your test project?

**Comment by beshkenadze** [comment]
I can confirm that adding the @better-auth/cli dependency causes an error.
To remove the error, simply delete the package and run it separately.

**Comment by ymc9** [comment]
The issue is caused by conflicting dependency version of "cheverotain" by better-auth CLI and ZenStack. Adding a version override to keep them consistent should resolve the issue.
