### ISSUE TITLE
Provide proper stacktrace in errors

### ISSUE THREAD

**Issue by sidharthv96** [zenstackhq/zenstack#384]
**Is your feature request related to a problem? Please describe.**
When an error is thrown, it's impossible to see in the stack trace where exactly the call came from. 

```
Error: denied by policy: diagramDocument entities failed 'update' check, 1 entity failed policy check
    at PolicyUtil.deniedByPolicy (/Users/sidv/dev/mc-collab/node_modules/.pnpm/@zenstackhq+runtime@1.0.0-alpha.113_@prisma+client@4.12.0/node_modules/@zenstackhq/runtime/enhancements/policy/policy-utils.js:646:16)
    at PolicyUtil.<anonymous> (/Users/sidv/dev/mc-collab/node_modules/.pnpm/@zenstackhq+runtime@1.0.0-alpha.113_@prisma+client@4.12.0/node_modules/@zenstackhq/runtime/enhancements/policy/policy-utils.js:712:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sidv/dev/mc-collab/node_modules/.pnpm/@zenstackhq+runtime@1.0.0-alpha.113_@prisma+client@4.12.0/node_modules/@zenstackhq/runtime/enhancements/policy/policy-utils.js:6:58)
```

**Describe the solution you'd like**
The call location should be included in the stacktrace. 

**Describe alternatives you've considered**

Current workaround

I added a console.trace in the getPrisma call so I can check that trace before the error. 
But it pollutes the console as it runs on every getPrisma call (even ones that don't error)

```ts
// Gets a Prisma client bound to the current user identity
export function getPrisma({ id }: { id?: string } = {}) {
  // eslint-disable-next-line no-console
  console.trace(`getPrisma called with id: ${id ?? 'undefined'}`);
  const user = id ? { id } : undefined;
  return withPolicy(dangerousPrismaDoNotUse, {
    user
  });
}
```

Which gives me stacktrace of my app's files.
```
Trace: getPrisma called with id: undefined
    at Module.getPrisma (/src/lib/server/prisma.ts:29:11)
    at Module.updateDocument (/src/lib/server/services/documentService.ts:61:31)
    at Module.getRawDiagram (/src/routes/raw/[diagramDocumentID]/rawHandler.ts:38:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional context**

**Comment by ymc9** [comment]
Hi @sidharthv96 , this has been improved in the latest beta.1 release.
